[2023-03-28T18:19:40.448+0000] {processor.py:153} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:19:40.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:19:40.462+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:19:40.459+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:19:42.566+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:19:42.556+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:19:42.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:19:42.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.219 seconds
[2023-03-28T18:20:12.895+0000] {processor.py:153} INFO - Started process (PID=200) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:20:12.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:20:12.917+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:20:12.917+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:20:15.366+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:20:15.345+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:20:15.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:20:15.454+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.609 seconds
[2023-03-28T18:20:46.022+0000] {processor.py:153} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:20:46.025+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:20:46.030+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:20:46.029+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:20:46.765+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:20:46.759+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:20:46.771+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:20:46.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.834 seconds
[2023-03-28T18:21:20.375+0000] {processor.py:153} INFO - Started process (PID=285) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:21:20.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:21:20.384+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:21:20.384+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:21:23.861+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:21:23.830+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:21:23.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:21:24.208+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.848 seconds
[2023-03-28T18:21:55.017+0000] {processor.py:153} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:21:55.030+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:21:55.062+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:21:55.060+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:22:01.454+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:22:01.412+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:22:01.456+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:22:01.623+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 6.655 seconds
[2023-03-28T18:22:32.272+0000] {processor.py:153} INFO - Started process (PID=357) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:22:32.288+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:22:32.290+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:22:32.290+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:22:35.131+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:22:35.057+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:22:35.144+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:22:35.299+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.055 seconds
[2023-03-28T18:23:05.693+0000] {processor.py:153} INFO - Started process (PID=392) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:23:05.701+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:23:05.714+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:23:05.713+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:23:09.284+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:23:09.250+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:23:09.289+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:23:09.425+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.753 seconds
[2023-03-28T18:23:40.415+0000] {processor.py:153} INFO - Started process (PID=431) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:23:40.431+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:23:40.435+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:23:40.435+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:23:41.505+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:23:41.488+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:23:41.515+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:23:41.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.247 seconds
[2023-03-28T18:24:12.016+0000] {processor.py:153} INFO - Started process (PID=466) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:24:12.023+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:24:12.033+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:24:12.032+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:24:12.617+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:24:12.613+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:24:12.620+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:24:12.667+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.661 seconds
[2023-03-28T18:27:11.878+0000] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:27:11.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:27:11.963+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:27:11.962+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:27:16.919+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:27:16.912+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:27:16.923+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:27:17.054+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 5.213 seconds
[2023-03-28T18:27:48.445+0000] {processor.py:153} INFO - Started process (PID=217) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:27:48.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:27:48.480+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:27:48.479+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:27:53.161+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:27:53.150+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:27:53.162+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:27:53.227+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 4.818 seconds
[2023-03-28T18:28:24.671+0000] {processor.py:153} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:28:24.762+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:28:24.857+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:28:24.839+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:28:33.426+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:28:33.424+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:28:33.435+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:28:33.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 9.222 seconds
[2023-03-28T18:29:03.953+0000] {processor.py:153} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:29:03.961+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:29:04.001+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:29:03.988+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:29:06.769+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:29:06.752+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:29:06.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:29:07.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.171 seconds
[2023-03-28T18:29:37.581+0000] {processor.py:153} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:29:37.614+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:29:37.622+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:29:37.621+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:29:39.477+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:29:39.466+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:29:39.484+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:29:39.560+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.992 seconds
[2023-03-28T18:30:10.607+0000] {processor.py:153} INFO - Started process (PID=356) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:30:10.621+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:30:10.623+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:30:10.623+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:30:12.978+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:30:12.938+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:30:12.988+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:30:13.117+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.586 seconds
[2023-03-28T18:30:44.682+0000] {processor.py:153} INFO - Started process (PID=401) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:30:44.689+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:30:44.710+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:30:44.710+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:30:46.293+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:30:46.284+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:30:46.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:30:46.444+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.771 seconds
[2023-03-28T18:31:17.420+0000] {processor.py:153} INFO - Started process (PID=438) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:31:17.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:31:17.476+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:31:17.476+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:31:18.700+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:31:18.696+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:31:18.701+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:31:18.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.335 seconds
[2023-03-28T18:31:49.353+0000] {processor.py:153} INFO - Started process (PID=471) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:31:49.369+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:31:49.371+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:31:49.371+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:31:51.876+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:31:51.866+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:31:51.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:31:51.961+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.648 seconds
[2023-03-28T18:32:22.748+0000] {processor.py:153} INFO - Started process (PID=519) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:32:22.750+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:32:22.754+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:32:22.752+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:32:24.094+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:32:24.090+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:32:24.099+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:32:24.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.412 seconds
[2023-03-28T18:32:55.226+0000] {processor.py:153} INFO - Started process (PID=555) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:32:55.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:32:55.281+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:32:55.268+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:33:02.136+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:33:02.136+0000] {process_utils.py:256} INFO - Waiting up to 5 seconds for processes to exit...
[2023-03-28T18:33:02.471+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:33:02.470+0000] {process_utils.py:256} INFO - Waiting up to 5 seconds for processes to exit...
[2023-03-28T18:34:51.215+0000] {processor.py:153} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:34:51.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:34:51.233+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:34:51.232+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:34:52.453+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:34:52.444+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:34:52.455+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:34:52.513+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.309 seconds
[2023-03-28T18:35:22.844+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:35:22.848+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:35:22.862+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:35:22.862+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:35:23.576+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:35:23.570+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:35:23.578+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:35:23.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.775 seconds
[2023-03-28T18:35:54.019+0000] {processor.py:153} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:35:54.024+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:35:54.034+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:35:54.033+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:35:55.465+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:35:55.456+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:35:55.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:35:55.529+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.526 seconds
[2023-03-28T18:36:26.006+0000] {processor.py:153} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:36:26.007+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:36:26.017+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:36:26.017+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:36:27.630+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:36:27.622+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:36:27.632+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:36:27.710+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.736 seconds
[2023-03-28T18:36:57.885+0000] {processor.py:153} INFO - Started process (PID=324) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:36:57.906+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:36:57.934+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:36:57.926+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:36:58.788+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:36:58.783+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:36:58.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:36:58.822+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.946 seconds
[2023-03-28T18:37:30.278+0000] {processor.py:153} INFO - Started process (PID=353) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:37:30.279+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:37:30.283+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:37:30.282+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:37:31.567+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:37:31.563+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:37:31.568+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:37:31.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.373 seconds
[2023-03-28T18:38:02.602+0000] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:38:02.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:38:02.613+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:38:02.613+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:38:04.113+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:38:04.108+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:38:04.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:38:04.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.598 seconds
[2023-03-28T18:38:36.356+0000] {processor.py:153} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:38:36.359+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:38:36.371+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:38:36.371+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:38:38.683+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:38:38.679+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:38:38.685+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:38:38.719+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.605 seconds
[2023-03-28T18:39:09.197+0000] {processor.py:153} INFO - Started process (PID=468) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:39:09.211+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:39:09.215+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:39:09.215+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:39:11.002+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:39:10.978+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:39:11.017+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:39:11.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.021 seconds
[2023-03-28T18:39:41.494+0000] {processor.py:153} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:39:41.507+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:39:41.514+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:39:41.513+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:39:42.171+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:39:42.167+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:39:42.173+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:39:42.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.730 seconds
[2023-03-28T18:40:13.125+0000] {processor.py:153} INFO - Started process (PID=540) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:40:13.126+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:40:13.130+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:40:13.130+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:40:13.854+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:40:13.848+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:40:13.856+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:40:13.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.782 seconds
[2023-03-28T18:40:44.621+0000] {processor.py:153} INFO - Started process (PID=575) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:40:44.625+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:40:44.638+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:40:44.638+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:40:45.281+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:40:45.277+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ImportError: cannot import name 'care_providers' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:40:45.282+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:40:45.312+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.710 seconds
[2023-03-28T18:42:41.530+0000] {processor.py:153} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:42:41.535+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:42:41.546+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:42:41.546+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:42:41.605+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:42:41.600+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import care_providers
ModuleNotFoundError: No module named 'operators.careProviders'
[2023-03-28T18:42:41.618+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:42:41.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 0.310 seconds
[2023-03-28T18:43:15.201+0000] {processor.py:153} INFO - Started process (PID=210) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:15.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:43:15.215+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:43:15.214+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:18.391+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:43:18.387+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.care_providers import care_providers
ImportError: cannot import name 'care_providers' from 'operators.care_providers' (/opt/airflow/dags/operators/care_providers.py)
[2023-03-28T18:43:18.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:18.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.284 seconds
[2023-03-28T18:43:22.594+0000] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:22.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:43:22.633+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:43:22.633+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:23.947+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:43:23.943+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:43:23.954+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:24.042+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.456 seconds
[2023-03-28T18:43:54.805+0000] {processor.py:153} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:43:54.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:43:54.843+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:43:54.842+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:45:54.192+0000] {processor.py:153} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:45:54.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:45:54.223+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:45:54.223+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:45:55.982+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:45:55.974+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:45:55.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:45:56.075+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.901 seconds
[2023-03-28T18:46:26.404+0000] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:46:26.407+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:46:26.415+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:46:26.415+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:46:29.412+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:46:29.408+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:46:29.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:46:29.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.168 seconds
[2023-03-28T18:47:00.429+0000] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:47:00.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:47:00.438+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:47:00.438+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:47:01.965+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:47:01.938+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:47:01.967+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:47:02.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.867 seconds
[2023-03-28T18:51:08.520+0000] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:51:08.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:51:08.534+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:51:08.534+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:51:17.530+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:51:17.414+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:51:17.569+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:51:18.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 9.619 seconds
[2023-03-28T18:51:49.947+0000] {processor.py:153} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:51:49.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:51:50.003+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:51:50.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:51:59.015+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:51:59.000+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:51:59.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:51:59.200+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 9.913 seconds
[2023-03-28T18:52:29.994+0000] {processor.py:153} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:52:30.009+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:52:30.033+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:52:30.033+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:52:36.192+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:52:36.182+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:52:36.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:52:36.464+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 6.594 seconds
[2023-03-28T18:58:17.263+0000] {processor.py:153} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:58:17.275+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:58:17.288+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:58:17.281+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:58:23.968+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:58:23.596+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:58:24.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:58:25.043+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 7.870 seconds
[2023-03-28T18:58:55.742+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:58:55.755+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:58:55.758+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:58:55.758+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:06.260+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:59:06.239+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 8, in <module>
    from operators.careProviders import main
ImportError: cannot import name 'main' from 'operators.careProviders' (/opt/airflow/dags/operators/careProviders.py)
[2023-03-28T18:59:06.274+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:06.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 10.760 seconds
[2023-03-28T18:59:24.784+0000] {processor.py:153} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:24.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:59:24.788+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:59:24.787+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:25.725+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:59:25.723+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_cube.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_cube.py", line 56, in <module>
    op_kwargs={"consumer": care_providers},
NameError: name 'care_providers' is not defined
[2023-03-28T18:59:25.726+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:25.783+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.005 seconds
[2023-03-28T18:59:38.121+0000] {processor.py:153} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:38.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T18:59:38.141+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:59:38.140+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:39.935+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T18:59:40.806+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:59:40.785+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T18:59:40.934+0000] {logging_mixin.py:137} INFO - [2023-03-28T18:59:40.934+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T18:59:41.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.024 seconds
[2023-03-28T19:00:12.102+0000] {processor.py:153} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:00:12.133+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:00:12.194+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:00:12.166+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:00:20.333+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:00:21.672+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:00:21.671+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:00:21.794+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:00:21.794+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:00:21.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 9.883 seconds
[2023-03-28T19:00:53.111+0000] {processor.py:153} INFO - Started process (PID=346) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:00:53.209+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:00:53.218+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:00:53.217+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:01:01.045+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:01:02.998+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:01:02.998+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:01:03.127+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:01:03.126+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:01:03.426+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 10.406 seconds
[2023-03-28T19:01:34.366+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:01:34.369+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:01:34.374+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:01:34.374+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:01:35.355+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:01:36.240+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:01:36.239+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:01:36.307+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:01:36.307+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:01:36.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.022 seconds
[2023-03-28T19:02:11.925+0000] {processor.py:153} INFO - Started process (PID=437) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:02:11.943+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:02:11.946+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:02:11.945+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:02:16.916+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:02:17.452+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:02:17.451+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:02:18.269+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:02:18.269+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:02:18.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 6.721 seconds
[2023-03-28T19:03:02.401+0000] {processor.py:153} INFO - Started process (PID=485) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:03:02.470+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:03:02.529+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:03:02.528+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:03:06.455+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:03:08.258+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:03:08.257+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:03:08.400+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:03:08.398+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:03:08.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 6.210 seconds
[2023-03-28T19:03:39.384+0000] {processor.py:153} INFO - Started process (PID=525) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:03:39.397+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:03:39.414+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:03:39.413+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:03:40.995+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:03:42.239+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:03:42.238+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:03:42.391+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:03:42.390+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:03:42.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.122 seconds
[2023-03-28T19:04:15.859+0000] {processor.py:153} INFO - Started process (PID=560) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:04:15.872+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:04:15.887+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:04:15.886+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:04:17.847+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:04:19.474+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:04:19.473+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:04:19.556+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:04:19.556+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:04:19.634+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.814 seconds
[2023-03-28T19:04:42.197+0000] {processor.py:153} INFO - Started process (PID=580) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:04:42.209+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:04:42.215+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:04:42.214+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:04:45.927+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:04:46.307+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:04:46.299+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:04:51.368+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:04:51.368+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:04:51.666+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 9.494 seconds
[2023-03-28T19:05:22.968+0000] {processor.py:153} INFO - Started process (PID=628) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:05:22.983+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:05:23.000+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:05:22.999+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:05:27.621+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:05:30.351+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:05:30.349+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:05:31.489+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:05:31.489+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:05:31.918+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 9.001 seconds
[2023-03-28T19:06:02.341+0000] {processor.py:153} INFO - Started process (PID=674) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:06:02.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:06:02.398+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:06:02.394+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:06:04.101+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:06:04.317+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:06:04.316+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:06:04.842+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:06:04.841+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:06:04.951+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.640 seconds
[2023-03-28T19:06:35.375+0000] {processor.py:153} INFO - Started process (PID=714) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:06:35.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:06:35.397+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:06:35.397+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:06:36.913+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:06:37.687+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:06:37.686+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:06:37.789+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:06:37.789+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:06:37.963+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.597 seconds
[2023-03-28T19:07:08.086+0000] {processor.py:153} INFO - Started process (PID=749) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:07:08.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:07:08.101+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:07:08.100+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:07:09.420+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:07:09.739+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:07:09.739+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:07:09.806+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:07:09.806+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:07:10.801+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.729 seconds
[2023-03-28T19:07:40.989+0000] {processor.py:153} INFO - Started process (PID=785) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:07:41.018+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:07:41.026+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:07:41.026+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:07:41.885+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:07:42.357+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:07:42.357+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:07:42.407+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:07:42.407+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:07:42.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.522 seconds
[2023-03-28T19:08:12.892+0000] {processor.py:153} INFO - Started process (PID=820) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:08:12.895+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:08:12.898+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:08:12.897+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:08:14.652+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:08:15.527+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:08:15.526+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:08:15.598+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:08:15.597+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:08:15.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.782 seconds
[2023-03-28T19:08:46.505+0000] {processor.py:153} INFO - Started process (PID=861) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:08:46.514+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:08:46.517+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:08:46.516+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:08:49.754+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:08:50.611+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:08:50.610+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:08:51.808+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:08:51.808+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:08:52.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 6.445 seconds
[2023-03-28T19:12:58.010+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:12:58.024+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:12:58.030+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:12:58.030+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:13:01.387+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:13:01.518+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:13:01.518+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:13:01.832+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:13:01.832+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:13:01.919+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.927 seconds
[2023-03-28T19:13:34.495+0000] {processor.py:153} INFO - Started process (PID=235) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:13:34.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:13:34.505+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:13:34.503+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:13:35.611+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:13:35.703+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:13:35.702+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:13:36.256+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:13:36.256+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:13:36.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.925 seconds
[2023-03-28T19:14:07.570+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:14:07.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:14:07.653+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:14:07.653+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:14:09.699+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:14:10.675+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:14:10.674+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:14:10.800+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:14:10.800+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:14:10.944+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.385 seconds
[2023-03-28T19:14:46.662+0000] {processor.py:153} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:14:46.677+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:14:46.699+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:14:46.695+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:14:48.966+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:14:49.534+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:14:49.533+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:14:49.667+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:14:49.667+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:14:49.818+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 3.193 seconds
[2023-03-28T19:15:23.876+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:15:23.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:15:24.058+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:15:23.949+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:15:27.041+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:15:28.672+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:15:28.670+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:15:28.863+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:15:28.863+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:15:28.977+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 5.316 seconds
[2023-03-28T19:16:01.631+0000] {processor.py:153} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:16:01.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:16:01.647+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:16:01.647+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:16:02.172+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:16:02.568+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:16:02.567+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:16:02.604+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:16:02.603+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:16:02.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 1.026 seconds
[2023-03-28T19:16:35.261+0000] {processor.py:153} INFO - Started process (PID=422) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:16:35.281+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:16:35.284+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:16:35.284+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:16:37.036+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:16:38.721+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:16:38.720+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:16:40.215+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:16:40.215+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:16:40.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 5.357 seconds
[2023-03-28T19:20:35.962+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:20:35.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:20:35.978+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:20:35.978+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:20:58.584+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:20:59.830+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:20:59.825+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:21:17.022+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:21:17.022+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:21:18.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 42.260 seconds
[2023-03-28T19:23:23.580+0000] {processor.py:153} INFO - Started process (PID=194) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:23:23.648+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:23:23.775+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:23:23.775+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:23:31.744+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:23:32.366+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:23:32.365+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:23:33.766+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:23:33.766+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:23:33.882+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 10.356 seconds
[2023-03-28T19:24:04.329+0000] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:24:04.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:24:04.427+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:24:04.424+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:24:06.246+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:24:07.029+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:24:07.022+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:24:08.099+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:24:08.098+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:24:08.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 4.578 seconds
[2023-03-28T19:24:39.626+0000] {processor.py:153} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:24:39.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:24:39.633+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:24:39.630+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:24:42.092+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:24:43.520+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:24:43.519+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:24:43.617+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:24:43.617+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:24:43.704+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 4.110 seconds
[2023-03-28T19:25:14.954+0000] {processor.py:153} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:25:14.965+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:25:15.086+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:25:14.990+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:25:18.666+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:25:20.302+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:25:20.301+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:25:20.454+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:25:20.454+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:25:20.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 5.674 seconds
[2023-03-28T19:25:51.581+0000] {processor.py:153} INFO - Started process (PID=347) to work on /opt/airflow/dags/dag_cube.py
[2023-03-28T19:25:51.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_cube.py for tasks to queue
[2023-03-28T19:25:51.596+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:25:51.596+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:25:52.672+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data-cubes']) retrieved from /opt/airflow/dags/dag_cube.py
[2023-03-28T19:25:53.318+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:25:53.318+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-28T19:25:53.476+0000] {logging_mixin.py:137} INFO - [2023-03-28T19:25:53.476+0000] {dag.py:3444} INFO - Setting next_dagrun for data-cubes to None, run_after=None
[2023-03-28T19:25:53.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_cube.py took 2.059 seconds
